apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: kaap74zd7-go 
  janus-idp.io/tekton: kaap74zd7-go
  backstage.io/kubernetes-id: kaap74zd7-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kaap74zd7-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml