apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kaap74zd7-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kaap74zd7-go 
  name: kaap74zd7-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kaap74zd7-go 
